### ISSUE TITLE
[Question] Not applied after installation

### ISSUE THREAD

**Issue by tan-wei** [amaanq/tree-sitter-doxygen#3]
First, thanks for this repo.

But after I've installed the tree-sitter parser by:
```lua
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.doxygen = {
  install_info = {
    url = "https://github.com/amaanq/tree-sitter-doxygen", -- local path or git repo
    files = { "src/parser.c", "src/scanner.c" }, -- note that some parsers also require src/scanner.c or src/scanner.cc
  },
  filetype = "cpp", -- if filetype does not match the parser name
}
```
and then `:TSinstall doxygen`, I can confirmed that the parser is sucessfully installed.
However, the doxygen comment in c/c++ is not highlighted.
Is my `filetype` set wrong? Thanks!

**Comment by tan-wei** [comment]
`TSModuleInfo`:
![图片](https://github.com/amaanq/tree-sitter-doxygen/assets/28227509/2d857d14-0ad1-43f6-a311-8990df9801a4)

**Comment by amaanq** [comment]
parser installation doesn't add queries

**Comment by tan-wei** [comment]
Got it. Thanks.

**Comment by amaanq** [comment]
It's available now, do let me know of *parsing* issues in this repo though

**Comment by tan-wei** [comment]
Any special installation step needed?
