### ISSUE TITLE
code indents

### ISSUE THREAD

**Issue by Decodetalkers** [amaanq/tree-sitter-doxygen#5]
like
```
@class DFileWatcherManager
@brief DFileWatcherManager xxx
@details

` ` `cpp
int main() {

}
` ` `
```

![image](https://github.com/amaanq/tree-sitter-doxygen/assets/60290287/091a9700-9900-4911-8b5e-107123f09aa8)

it breaks

**Comment by Decodetalkers** [comment]
I think doxygen should make code can be indented

**Comment by amaanq** [comment]
interesting, is the code block notation documented anywhere?

**Comment by Decodetalkers** [comment]
doxygen has markdown support, this parted seems is the same as markdown

https://www.doxygen.nl/manual/markdown.html#markdown_dox

you can test the doxygen from kde, they use code block a lot

**Comment by Decodetalkers** [comment]
or you can take this one as example

https://github.com/linuxdeepin/dtkcore/blob/master/docs/global/dconfig.zh_CN.dox

I am supperised that you make a doxygen hightlight, thanks for your effort!!

**Comment by amaanq** [comment]
wow, that's an awesome corpus - thanks!

**Comment by amaanq** [comment]
![image](https://github.com/amaanq/tree-sitter-doxygen/assets/29718261/ffa0aed9-efb6-4740-afc4-94c5d3f8ac05)

:grin:

**Comment by Decodetalkers** [comment]
👍 great

**Comment by amaanq** [comment]
Just note that delimiters must be immediate, in your example you spaced them out, I'm not sure if that's valid

**Comment by Decodetalkers** [comment]
You mean I type 

` ` `

It should be 
```

But because of I need to to show how they are. And if I use ```, the code block will be rendered strange on GitHub

**Comment by amaanq** [comment]
ok it's done as expected then, thanks!
